---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-controller-deploy
  namespace: tkg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapp-controller-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kapp-controller-deploy
  namespace: tkg-system
